Initialize packets, so the on 'message' handler doesn't return undefined.
When DNSPacket.parse throws an error the on 'message' handler returns undefined. Then, the decodePackets assumes that packets is an array and calls its forEach method ...
Here's a stack trace:

./node_modules/mdns-js/lib/decoder.js:98
  packets.forEach(function (packet) {
          ^
TypeError: Cannot call method 'forEach' of undefined
    at Object.module.exports.decodePackets (./node_modules/mdns-js/lib/decoder.js:98:11)
    at internal.onMessage (./node_modules/mdns-js/lib/browser.js:23:22)
    at EventEmitter.emit (events.js:106:17)
    at Socket.<anonymous> (./node_modules/mdns-js/lib/networking.js:141:10)
    at Socket.EventEmitter.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:440:8)